### ISSUE TITLE
Connect rubocop gem

### ISSUE THREAD

**Issue by galulex** [toysshopdevelop/toysshop#26]
1. Add rubocop to Gemfile
2. Create .rubocop.yml with next configs

``` yaml
AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'Gemfile'
Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 20
```
