### ISSUE TITLE
Admin namespace

### ISSUE THREAD

**Issue by galulex** [toysshopdevelop/toysshop#6]
Add heroku env variables for admin login and password (ADMIN_LOGIN, ADMIN_PASSWORD)

use it in `secrets.yml`

``` yaml
development:
  admin_login: admin
  admin_password: password
production:
  admin_login: <%= ENV['ADMIN_LOGIN'] %>
  admin_password: <%= ENV['ADMIN_PASSWORD'] %>
```

Wrap admin functionality with admin namespcase

`admin/products`, `admin/categories`

Add http basic auth
